#image: alpine

stages:
  - download
  - save
  - deploy

download-usherbrooke.ca/coronavirus/:
  stage: download
  script:
    - apk update && apk add wget
    - ./getUrls.sh
  artifacts:
    paths:
      - html

save-change:
  stage: save
  script:
    - echo "Commit will happened here"

pages:
  stage: deploy
  script:
    - ls -la
    - mv html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
