image: alpine

stages:
  - download
  - save
  - deploy

usherbrooke.ca/coronavirus/:
  stage: download
  script:
    - apk update && apk add wget
    - ./getUrls.sh
  artifacts:
    paths:
      - html

save-change:
  stage: save
  script:
    - apk update && apk add git
    - git config --list
    - git config --list --show-origin
    - git status
    - git add *.html
    - git status

pages:
  stage: deploy
  script:
    - ls -la
    - mv html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
