image: alpine

stages:
  - download
  - save
  - deploy

usherbrooke.ca/coronavirus/:
  stage: download
  script:
    - apk update && apk add wget
    - ./getUrls.sh
  artifacts:
    paths:
      - html

save-change:
  stage: save
  script:
    - apk update && apk add git
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git checkout $CI_DEFAULT_BRANCH
    - git pull
    - git add *.html
    - git commit -m "Update $(date +%F) $(date +%R)"
    - git status
    - git push https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/COVID-update/collect-usherbrooke.ca.git $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - ls -la
    - mv html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
