image: alpine

stages:
  - download
  - save
  - deploy

usherbrooke.ca/coronavirus/:
  stage: download
  script:
    - apk update && apk add wget
    - ./getUrls.sh
  artifacts:
    paths:
      - html

save-change:
  stage: save
  script:
    - whoami
    - apk update && apk add git perl
    - echo $CI_BUILD_REPO

    - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
    - echo $CI_BUILD_REPO
    - echo $CI_PUSH_REPO

    - git checkout $CI_DEFAULT_BRANCH
    - git config user.name "$RUNNER_NAME"
    - git config user.email "$RUNNER_EMAIL"
    - git remote set-url --push origin "${CI_PUSH_REPO}"
    - git config --list --show-origin
    - git pull
    - git status
    - git add *.html
    - git status
    - git commit -m "Update $(date +%F) $(date +%R)"
    - git status
    - git log --graph
    - git push

pages:
  stage: deploy
  script:
    - ls -la
    - mv html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
