name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  download:
    name: usherbrooke.ca/coronavirus
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          - apk update && apk add wget
          - ./getUrls.sh
      - name: Upload website to artifact
        uses: actions/upload-artifact@v2
        with:
          path: html
  save:
    name: save-change
    needs: download
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: html
      - name: Commit files
        run: |
          - git config user.email "action@github.com"
          - git config user.name "GitHub Action"
          - git add *.html
          - git commit -m "Update $(date +%F) $(date +%R)"
          - git status
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
